# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-a177c4fd-b427-4321-beed-87cc1a3271d6";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-a177c4fd-b427-4321-beed-87cc1a3271d6".device =
    "/dev/disk/by-uuid/a177c4fd-b427-4321-beed-87cc1a3271d6";
  boot.initrd.luks.devices."luks-ff21dae6-bab5-49d2-b6e3-77b6533f42fe".device =
    "/dev/disk/by-uuid/ff21dae6-bab5-49d2-b6e3-77b6533f42fe";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A81C-DB73";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-ff21dae6-bab5-49d2-b6e3-77b6533f42fe"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
